/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminStats {
  'avgPlatformRating' : number,
  'totalSeekers' : bigint,
  'totalProviders' : bigint,
  'pendingProviderApprovals' : bigint,
  'totalCategories' : bigint,
  'totalReviews' : bigint,
  'totalInquiries' : bigint,
}
export interface BilingualText { 'en' : string, 'hi' : string }
export interface Category {
  'id' : CategoryId,
  'displayOrder' : bigint,
  'icon' : string,
  'name' : BilingualText,
  'color' : string,
  'description' : BilingualText,
  'isActive' : boolean,
}
export type CategoryId = bigint;
export interface CategoryInput {
  'displayOrder' : bigint,
  'icon' : string,
  'name' : BilingualText,
  'color' : string,
  'description' : BilingualText,
}
export type ClassSubCategory = { 'coaching' : null } |
  { 'yoga' : null } |
  { 'fitness' : null } |
  { 'dhyan' : null };
export interface ClassVideo {
  'id' : bigint,
  'subCategory' : ClassSubCategory,
  'title' : string,
  'description' : string,
  'isActive' : boolean,
  'providerId' : ProviderId,
  'uploadedAt' : bigint,
  'fileKey' : string,
}
export interface ClassVideoInput {
  'subCategory' : ClassSubCategory,
  'title' : string,
  'description' : string,
  'fileKey' : string,
}
export interface Inquiry {
  'id' : InquiryId,
  'status' : InquiryStatus,
  'serviceName' : string,
  'createdAt' : Timestamp,
  'seekerId' : UserId,
  'preferredContact' : string,
  'message' : string,
  'providerId' : ProviderId,
}
export type InquiryId = bigint;
export interface InquiryInput {
  'serviceName' : string,
  'preferredContact' : string,
  'message' : string,
  'providerId' : ProviderId,
}
export type InquiryStatus = { 'closed' : null } |
  { 'responded' : null } |
  { 'pending' : null };
export type OpenRegisterResult = { 'ok' : OpenUserRecord } |
  { 'err' : string };
export interface OpenUserInput {
  'serviceCategory' : string,
  'city' : string,
  'name' : string,
  'role' : Role,
  'email' : string,
  'state' : string,
  'phone' : string,
}
export interface OpenUserRecord {
  'id' : bigint,
  'serviceCategory' : string,
  'city' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'role' : Role,
  'email' : string,
  'state' : string,
  'phone' : string,
}
export interface Page {
  'total' : bigint,
  'page' : bigint,
  'pageSize' : bigint,
  'items' : Array<ProviderSummary>,
}
export interface Provider {
  'id' : ProviderId,
  'ownerName' : string,
  'city' : string,
  'userId' : UserId,
  'profileImage' : [] | [string],
  'createdAt' : Timestamp,
  'businessName' : string,
  'isActive' : boolean,
  'email' : string,
  'state' : string,
  'availableFrom' : [] | [string],
  'isVerified' : boolean,
  'contactAvailabilityEnabled' : [] | [boolean],
  'address' : string,
  'bioEn' : string,
  'bioHi' : string,
  'phone' : string,
  'servicesOffered' : Array<ServiceOffered>,
  'availableTo' : [] | [string],
  'serviceAreas' : Array<string>,
  'categoryIds' : Array<CategoryId>,
}
export interface ProviderFilter {
  'categoryId' : [] | [CategoryId],
  'city' : [] | [string],
  'state' : [] | [string],
}
export type ProviderId = bigint;
export interface ProviderInput {
  'ownerName' : string,
  'city' : string,
  'profileImage' : [] | [string],
  'businessName' : string,
  'email' : string,
  'state' : string,
  'availableFrom' : [] | [string],
  'contactAvailabilityEnabled' : [] | [boolean],
  'address' : string,
  'bioEn' : string,
  'bioHi' : string,
  'phone' : string,
  'servicesOffered' : Array<ServiceOffered>,
  'availableTo' : [] | [string],
  'serviceAreas' : Array<string>,
  'categoryIds' : Array<CategoryId>,
}
export interface ProviderSearchFilter {
  'categoryId' : [] | [CategoryId],
  'minRating' : [] | [number],
  'city' : [] | [string],
  'state' : [] | [string],
  'isVerified' : [] | [boolean],
  'searchQuery' : [] | [string],
}
export interface ProviderSummary {
  'id' : ProviderId,
  'ownerName' : string,
  'city' : string,
  'userId' : UserId,
  'profileImage' : [] | [string],
  'businessName' : string,
  'isActive' : boolean,
  'averageRating' : number,
  'state' : string,
  'isVerified' : boolean,
  'reviewCount' : bigint,
  'categoryIds' : Array<CategoryId>,
}
export interface Review {
  'id' : ReviewId,
  'createdAt' : Timestamp,
  'seekerId' : UserId,
  'comment' : string,
  'rating' : bigint,
  'providerId' : ProviderId,
}
export type ReviewId = bigint;
export interface ReviewInput {
  'comment' : string,
  'rating' : bigint,
  'providerId' : ProviderId,
}
export type Role = { 'admin' : null } |
  { 'provider' : null } |
  { 'seeker' : null };
export interface ServiceOffered {
  'title' : string,
  'description' : string,
  'availability' : string,
  'serviceId' : bigint,
  'price' : [] | [string],
}
export type Timestamp = bigint;
export interface User {
  'id' : UserId,
  'city' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'role' : Role,
  'email' : string,
  'state' : string,
  'phone' : string,
}
export type UserId = Principal;
export interface UserInput {
  'city' : string,
  'name' : string,
  'email' : string,
  'state' : string,
  'phone' : string,
}
export interface UserUpdateInput {
  'city' : string,
  'name' : string,
  'role' : [] | [Role],
  'email' : string,
  'state' : string,
  'phone' : string,
}
export interface _SERVICE {
  'addClassVideo' : ActorMethod<[ProviderId, ClassVideoInput], ClassVideo>,
  'addReview' : ActorMethod<[ReviewInput], Review>,
  'approveProvider' : ActorMethod<[ProviderId], boolean>,
  'checkContactAvailable' : ActorMethod<[ProviderId, string], boolean>,
  'createCategory' : ActorMethod<[CategoryInput], Category>,
  'createProviderProfile' : ActorMethod<[ProviderInput], Provider>,
  'deleteCategory' : ActorMethod<[CategoryId], boolean>,
  'deleteClassVideo' : ActorMethod<[bigint, ProviderId], boolean>,
  'disableProvider' : ActorMethod<[ProviderId], boolean>,
  'getAdminStats' : ActorMethod<[], AdminStats>,
  'getCategory' : ActorMethod<[CategoryId], [] | [Category]>,
  'getClassVideoById' : ActorMethod<[bigint], [] | [ClassVideo]>,
  'getClassVideosByProvider' : ActorMethod<[ProviderId], Array<ClassVideo>>,
  'getClassVideosBySubCategory' : ActorMethod<
    [ClassSubCategory],
    Array<ClassVideo>
  >,
  'getFeaturedProviders' : ActorMethod<[], Array<ProviderSummary>>,
  'getInquiriesByProvider' : ActorMethod<[ProviderId], Array<Inquiry>>,
  'getMyClassVideos' : ActorMethod<[ProviderId], Array<ClassVideo>>,
  'getMyInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getMyProfile' : ActorMethod<[], [] | [User]>,
  'getMyProviderProfile' : ActorMethod<[], [] | [Provider]>,
  'getMyReviews' : ActorMethod<[], Array<Review>>,
  'getOpenUserCount' : ActorMethod<[], bigint>,
  'getProvider' : ActorMethod<[ProviderId], [] | [Provider]>,
  'getProvidersByCategory' : ActorMethod<[CategoryId, bigint, bigint], Page>,
  'getReviewsByProvider' : ActorMethod<[ProviderId], Array<Review>>,
  'getVisitorStats' : ActorMethod<
    [],
    { 'totalVisits' : bigint, 'uniqueVisitors' : bigint }
  >,
  'listAllCategories' : ActorMethod<[], Array<Category>>,
  'listCategories' : ActorMethod<[], Array<Category>>,
  'listProviders' : ActorMethod<[ProviderFilter, bigint, bigint], Page>,
  'listUsers' : ActorMethod<[], Array<User>>,
  'openRegisterUser' : ActorMethod<[OpenUserInput], OpenRegisterResult>,
  'registerUser' : ActorMethod<[UserInput], User>,
  'searchProviders' : ActorMethod<[ProviderSearchFilter, bigint, bigint], Page>,
  'seedSampleData' : ActorMethod<[], boolean>,
  'setCategoryActive' : ActorMethod<[CategoryId, boolean], boolean>,
  'setUserRole' : ActorMethod<[UserId, Role], boolean>,
  'submitInquiry' : ActorMethod<[InquiryInput], Inquiry>,
  'toggleClassVideoActive' : ActorMethod<
    [bigint, ProviderId],
    [] | [ClassVideo]
  >,
  'trackVisit' : ActorMethod<
    [string],
    { 'totalVisits' : bigint, 'uniqueVisitors' : bigint }
  >,
  'updateCategory' : ActorMethod<[CategoryId, CategoryInput], [] | [Category]>,
  'updateInquiryStatus' : ActorMethod<
    [InquiryId, InquiryStatus],
    [] | [Inquiry]
  >,
  'updateProviderProfile' : ActorMethod<
    [ProviderId, ProviderInput],
    [] | [Provider]
  >,
  'updateUserProfile' : ActorMethod<[UserUpdateInput], [] | [User]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];